---
title: Exploring car number plates
author: Steven Wooding
date: '2022-04-11'
slug: exploring-car-number-plates
categories: []
tags:
  - brms
  - R
  - RStudio
subtitle: ''
summary: ''
authors: []
lastmod: '2022-04-11T19:46:10+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
```{r}
pacman::p_load(tidyverse, brms) 
```

```{r}
# Make up some data
# We seem to need data as a list with the number of each options
# Terminology: first half of the year: 'f', second half of the year: 's'

# number_plates <- data.frame(half_year = c("f", "f", "f", "f", "s", "s", "f", "f", "f", "s", "f", "s"))

number_plates = list(f = 8, s = 4)

half_year = list(f = 8, s = 4)

plates1.0 <-
  brm(data = number_plates, 
      family = binomial(link = "identity"),
      f | trials(12) ~ 1,
      prior(beta(1, 1), class = b, lb = 0, ub = 1),
      seed = 2,
      file = "fits/plates01.00")

print(plates1.0)

posterior_samples(plates1.0) %>% 
  mutate(n = "n = 12") %>%
  ggplot(aes(x = b_Intercept)) +
  geom_density(fill = "black") +
  scale_x_continuous("proportion registered in first half of year", limits = c(0, 1)) +
  theme(panel.grid = element_blank()) +
  facet_wrap(~ n)

```

